### ISSUE TITLE
How to get mlx5ctl.ko (ConnectX debug uAPI driver)

### ISSUE THREAD

**Issue by senofgithub** [saeedtx/mlx5ctl#3]
hello, i think [mlx5ctl] is useful, but how to get mlx5ctl.ko ?

thank you

**Comment by saeedtx** [comment]
Please refer to this kernel submission to get the kernel part and the user space that works with it:
https://lore.kernel.org/all/0-v2-940e479ceba9+3821-fwctl_jgg@nvidia.com/
it has mlx5_fwctl.ko and the new fwctl subsystem.

the user space to go with it is Jason's version :
https://github.com/jgunthorpe/mlx5ctl

**Comment by senofgithub** [comment]
> user space to go with it is Jason's version :

Thank you very much
